# Generated by Django 4.2.6 on 2023-10-27 15:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bodegas',
            fields=[
                ('id_bodega', models.AutoField(primary_key=True, serialize=False, verbose_name='Id Bodega')),
                ('nombre_bod', models.CharField(max_length=30, verbose_name='Nombre Bodega')),
            ],
        ),
        migrations.CreateModel(
            name='Categorias',
            fields=[
                ('id_cat', models.AutoField(primary_key=True, serialize=False, verbose_name='Id Categoria')),
                ('nombre_cat', models.CharField(max_length=20, verbose_name='Tipo de Categoria')),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id_cliente', models.AutoField(primary_key=True, serialize=False)),
                ('rut_empresa', models.IntegerField(unique=True)),
                ('razon_social', models.CharField(max_length=30)),
                ('direccion_empresa', models.CharField(max_length=30)),
                ('nombre_representante', models.CharField(max_length=30)),
                ('apellido_representante', models.CharField(max_length=20)),
                ('telefono', models.IntegerField(unique=True)),
                ('correo_empresa', models.EmailField(default='', max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Maquinaria',
            fields=[
                ('id_m', models.AutoField(primary_key=True, serialize=False)),
                ('sku', models.IntegerField(unique=True)),
                ('nombre_m', models.CharField(max_length=20, verbose_name='Nombre Maquinaria')),
                ('valor_dia', models.DecimalField(decimal_places=2, max_digits=10)),
                ('bodega_m', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='arriendo.bodegas')),
                ('categoria_m', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='arriendo.categorias', verbose_name='Categorias')),
            ],
        ),
        migrations.CreateModel(
            name='Arriendos',
            fields=[
                ('id_arriendo', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_arriendo', models.DateField()),
                ('fecha_inicio', models.DateField()),
                ('fecha_entrega', models.DateField(blank=True, null=True)),
                ('dias_arriendo', models.IntegerField(blank=True, null=True)),
                ('costo_total', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('bodega_arriendo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='arriendo.bodegas')),
                ('cliente_arriendo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='arriendo.cliente')),
                ('maquina_arriendo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='arriendo.maquinaria')),
            ],
        ),
    ]
