# Generated by Django 4.2.6 on 2023-10-13 01:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bodegas',
            fields=[
                ('id_bodega', models.AutoField(primary_key=True, serialize=False, verbose_name='Id Bodega')),
                ('nombre_bod', models.CharField(max_length=30, verbose_name='Nombre Bodega')),
            ],
        ),
        migrations.CreateModel(
            name='Categorias',
            fields=[
                ('id_cat', models.AutoField(primary_key=True, serialize=False, verbose_name='Id Categoria')),
                ('nombre_cat', models.CharField(max_length=20, verbose_name='Tipo de Categoria')),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id_cliente', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=20)),
                ('apellido', models.CharField(max_length=20)),
                ('rut', models.CharField(max_length=40)),
                ('telefono', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Maquinaria',
            fields=[
                ('id_m', models.AutoField(primary_key=True, serialize=False)),
                ('sku', models.CharField(max_length=20)),
                ('nombre_m', models.CharField(max_length=20)),
                ('estado', models.CharField(choices=[('disponible', 'Disponible'), ('no_disponible', 'No Disponible')], default='disponible', max_length=20)),
                ('bodega_m', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='arriendo.bodegas')),
                ('categoria_m', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='arriendo.categorias')),
            ],
        ),
        migrations.CreateModel(
            name='EstadoMaquinaria',
            fields=[
                ('id_estado', models.AutoField(primary_key=True, serialize=False)),
                ('estado', models.CharField(choices=[('Y', 'Disponible'), ('N', 'No Disponible')], default='Y', max_length=1)),
                ('nombre_est_maquina', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='arriendo.maquinaria')),
            ],
        ),
        migrations.CreateModel(
            name='Arriendos',
            fields=[
                ('id_arriendo', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_arriendo', models.DateField()),
                ('bodega_arriendo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='arriendo.bodegas')),
                ('cliente_arriendo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='arriendo.cliente')),
                ('maquina_arriendo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='arriendo.maquinaria')),
            ],
        ),
    ]
