# Generated by Django 4.2.6 on 2023-10-14 05:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('arriendo', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='maquinaria',
            name='estado',
        ),
        migrations.DeleteModel(
            name='EstadoMaquinaria',
        ),
    ]
